### ISSUE TITLE
缺少训练文件：关于网络训练提示的缺失文件

### ISSUE THREAD

**Issue by Tian14267** [looput/PSENet#5]
你好，我在用你的网络训练的时候，提示缺少 tf_extended 。请问这个文件在哪里？
还有，在ssd_vgg预处理的时候，提示config找不到。这个是VGG的参数情况，我也没找到。请问在什么地方？
File "/home/hj/smbshare/fffan/PSEnet/PSENet-Tensorflow-master/preprocessing/ssd_vgg_preprocessing.py", line 39, in <module>
    import config
ImportError: No module named 'config'
万分感谢！

**Comment by looput** [comment]
你好，这个文件已经上传，当时只用到了里面三行 ，代码整理忘记移除这个依赖，后续我移除下

**Comment by Tian14267** [comment]
你好，现在有这么个错误
File "/home/hj/smbshare/fffan/PSEnet/PSENet-Tensorflow-master/model/inference.py", line 26, in <module>
    from PSE_C import mylib
ValueError: source code string cannot contain null bytes
我想问下，mylib文件在哪啊？我看到都是C的文件，没有python的文件。

追问：我这边的很多文件都提示“source code string cannot contain null bytes“，这些文件必须用python的IDLE重新保存才可用。用pycharm什么的编辑，就会报那个错误。你知道什么原因吗？
非常感谢 @looput

**Comment by looput** [comment]
这应该是你没有编译`cd ./PSE_C;python setup.py build_ext --inplace`. 
我是用vscode, 没有遇到过这个问题 , 或许你可以参考这个链接 [link](https://blog.csdn.net/wm5920/article/details/80813607)

**Comment by Tian14267** [comment]
尴尬，我这边编译一直无法通过，一直报错，网上的很多方法都试了：
............
my_lib.h:2:1: error: stray ‘\362’ in program
my_lib.h:2:1: error: stray ‘\304’ in program
my_lib.h:2:1: error: stray ‘\300’ in program
my_lib.h:2:1: error: stray ‘\246’ in program
my_lib.h:2:1: error: stray ‘\231’ in program
my_lib.h:2:1: error: stray ‘\225’ in program
my_lib.h:2:1: error: stray ‘\274’ in program
my_lib.h:2:1: error: stray ‘\211’ in program
my_lib.h:2:1: error: stray ‘\23’ in program
my_lib.h:2:1: error: stray ‘\216’ in program
my_lib.h:2:1: error: stray ‘\320’ in program
my_lib.h:2:19: warning: missing terminating ' character
 yV 󅀦AeI¼Χºk˥ºb漭~`ܖL䦦跞n魲»
                             0.8Cb¿3
                   ^
my_lib.h:2:1: error: missing terminating ' character
 yV 󅀦AeI¼Χºk˥ºb漭~`ܖL䦦跞n魲»
                             0.8Cb¿3
 ^
XshellXshellXshellXshellIn file included from my_lib.cpp:305:0:
my_lib.h:1:2: error: expected declaration before ‘}’ token
 }Z   D   a]Z»N<xoݣ> þÿ                                                                                                             
  ^
In file included from /home/hj/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /home/hj/.local/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from my_lib.cpp:303:
/home/hj/.local/lib/python3.5/site-packages/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: ‘int _import_array()’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
error: command 'gcc' failed with exit status 1
我的是ubuntu系统，python3.5。python2好像也是类似的错误。
重装了python3-dev，libevent-dev，sudo apt-get groupinstall 'development tools'，可还是不行。
请问你知道怎么解决嘛？

**Comment by Tian14267** [comment]
@looput

**Comment by looput** [comment]
你尝试更新下numpy
我的版本如下：
`
numpy==1.15.4
python==3.6.8
gcc==5.4.0
`

**Comment by Tian14267** [comment]
你好，我的nump和gcc版本跟你一样。
另外，我在运行训练文件的时候，还是会报错。
2019-06-21 09:33:51.557059: W tensorflow/core/framework/op_kernel.cc:1261] Unknown: IndexError: index 16 is out of bounds for axis 0 with size 16
Traceback (most recent call last):
  File "/home/hj/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)
  File "/home/hj/smbshare/fffan/PSEnet/PSENet-Tensorflow-master/dataset/preprocess.py", line 150, in process_data_np
    if not label[i] :
IndexError: index 16 is out of bounds for axis 0 with size 16
请问这个问题该怎么修改？ @looput 
训练数据是 ctw1500

**Comment by Tian14267** [comment]
@looput
