### ISSUE TITLE
Value passed to parameter 'x' has DataType int32 not in list of allowed values: bfloat16, float16, float32, float64

### ISSUE THREAD

**Issue by Tian14267** [looput/PSENet#7]
又遇到两个问题。麻烦作者有空看一下哈。
第一个问题：python2 eval_metric.py  （用python2运行）
报错：('checkpoint_path:', 'Logs/train/')
[u'Logs/train/model.ckpt-149999']
==========run progrss 0 / 1============
Traceback (most recent call last):
  File "eval_metric.py", line 66, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "eval_metric.py", line 62, in main
    inference.eval_model(config, FLAGS,para_list=None,is_log=FLAGS.lg)
  File "/home/hj/smbshare/fffan/PSEnet/PSENet-Tensorflow-looput_new/PSENet-Tensorflow-master/model/inference.py", line 287, in eval_model
    image,scale=scale,out_shape=out_shape)
  File "/home/hj/smbshare/fffan/PSEnet/PSENet-Tensorflow-looput_new/PSENet-Tensorflow-master/dataset/preprocess.py", line 368, in preprocess_for_eval
    image_h=tf.cast(tf.rint(image_h/32)*32,tf.int32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 6346, in rint
    "Rint", x=x, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'x' has DataType int32 not in list of allowed values: bfloat16, float16, float32, float64

第二个问题：python3 eval_metric.py（用python3运行）
报错：
Traceback (most recent call last):
  File "eval_metric.py", line 66, in <module>
    tf.app.run()
  File "/home/hj/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "eval_metric.py", line 62, in main
    inference.eval_model(config, FLAGS,para_list=None,is_log=FLAGS.lg)
  File "/home/hj/smbshare/fffan/PSEnet/PSENet-Tensorflow-looput_new/PSENet-Tensorflow-master/model/inference.py", line 469, in eval_model
    json.dump(res, f, indent=2)
UnboundLocalError: local variable 'res' referenced before assignment
麻烦作者看下这两个问题怎么解决哈

**Comment by Tian14267** [comment]
@looput 麻烦看一下，大神

**Comment by looput** [comment]
我用的python3, 2出的问题不太清楚。
第二个问题说明调用测试脚本没有成功   https://github.com/looput/PSENet-Tensorflow/blob/689b00e4ab4fe14e1e8788cc31f98f24919a289f/model/inference.py#L458
这个测试代码只支持IC15数据集，其他数据集要用相应的脚本
